# Generated by Django 4.2.7 on 2026-03-05 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("senior_care", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="blood_sugar",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="oxygen_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="record_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("specialty", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("clinic_address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "senior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="senior_care.seniorprofile",
                    ),
                ),
            ],
        ),
    ]
