# Generated by Django 4.2.7 on 2026-03-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "senior_care",
            "0002_healthrecord_blood_sugar_healthrecord_oxygen_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("meal", "Meal"),
                            ("medicine", "Medicine"),
                            ("exercise", "Exercise"),
                            ("hygiene", "Hygiene"),
                            ("mood", "Mood/Social"),
                            ("rest", "Rest/Sleep"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "caretaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "senior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to="senior_care.seniorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
