# Generated by Django 4.2.7 on 2026-03-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("senior_care", "0004_seniorprofile_pair_code_is_connected"),
    ]

    operations = [
        migrations.AddField(
            model_name="caretakerprofile",
            name="availability_status",
            field=models.CharField(default="Full-time", max_length=50),
        ),
        migrations.AddField(
            model_name="caretakerprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caretakerprofile",
            name="specialization",
            field=models.CharField(
                blank=True, default="Professional Caretaker", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="availability_status",
            field=models.CharField(default="Part-time", max_length=50),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="specialization",
            field=models.CharField(blank=True, default="Volunteer", max_length=255),
        ),
    ]
