# Generated by Django 4.2.7 on 2026-03-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("senior_care", "0005_caretakerprofile_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seniorprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="medical_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="senior_photos/"),
        ),
        migrations.AddField(
            model_name="seniorprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senior_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
