# Generated by Django 4.2.7 on 2026-03-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("senior_care", "0007_volunteeremergency_helprequest_chatmessage_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volunteerrating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="volunteerrating",
            name="help_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="senior_care.helprequest",
            ),
        ),
        migrations.AddField(
            model_name="volunteerrating",
            name="senior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_ratings",
                to="senior_care.seniorprofile",
            ),
        ),
    ]
