# Generated by Django 4.2.7 on 2026-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("senior_care", "0008_alter_volunteerrating_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventregistration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("family", "Family Member"),
                    ("caretaker", "Caretaker"),
                    ("volunteer", "Volunteer"),
                    ("ngo", "NGO"),
                ],
                default="family",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventRegistration",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
