# Generated by Django 4.2.7 on 2026-04-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_care', '0009_remove_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', max_length=5),
        ),
        migrations.CreateModel(
            name='BuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
